apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqldb
data:
  instance_connection_name: qwiklabs-gcp-01-f0870e227732:us-central1:marketplace
  profile: staging
  project_id: qwiklabs-gcp-01-f0870e227732
  database_name: marketplace
  rds_hostname: "35.226.172.28"
  rds_db_name: marketplace
  rds_port: "3306"