---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: gcr.io/qwiklabs-gcp-01-997154ce00ff/inventory:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: mysqldb
        env:
          - name: db_username
            valueFrom:
              secretKeyRef:
                name: user-credentials
                key: username
          - name: db_password
            valueFrom:
              secretKeyRef:
                name: user-credentials
                key: password
        ports:
        - containerPort: 8080
---