apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: inventory
    service: inventory
spec:
  ports:
  - port: 8080
    nodePort: 30888
    name: http
  selector:
    app: inventory
---